"""
EvoBot Self-Evaluation and Evolution Framework

Implements the sense-act-evaluate-evolve loop. The robot scores its own
performance, accumulates performance data, and periodically generates
improvement proposals for human review.

Per Constitution Article 22: Self-evolution means better judgment, not
fewer constraints. The evolution engine can NEVER propose changes that
reduce safety margins.

Per Constitution Article 1.4: Steward, not sovereign. Proposals that
affect safety behavior require human approval.
"""

import time
from collections import deque
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from logger import Logger


@dataclass
class CycleScore:
    """
    Evaluation of a single main-loop cycle.

    Scored on five dimensions, each 0.0 (worst) to 1.0 (best).
    """
    timestamp: float = 0.0
    safety: float = 1.0       # 0.0 = e_stop fired, 1.0 = clean cycle
    progress: float = 0.5     # 0.0 = no progress, 1.0 = objective achieved
    efficiency: float = 0.5   # 0.0 = wasteful, 1.0 = optimal
    smoothness: float = 1.0   # 0.0 = erratic, 1.0 = smooth
    prediction_accuracy: float = 0.5  # 0.0 = wildly wrong, 1.0 = predicted correctly
    composite: float = 0.0    # Weighted average (computed)
    notes: List[str] = field(default_factory=list)

    def compute_composite(self, weights: Optional[Dict[str, float]] = None) -> float:
        """
        Compute weighted average composite score.

        Args:
            weights: Dict mapping dimension name to weight. Defaults to
                     safety-heavy weighting.

        Returns:
            Composite score 0.0-1.0
        """
        if weights is None:
            weights = {
                "safety": 0.35,
                "progress": 0.20,
                "efficiency": 0.15,
                "smoothness": 0.15,
                "prediction_accuracy": 0.15,
            }
        total_weight = sum(weights.values())
        self.composite = (
            weights.get("safety", 0) * self.safety
            + weights.get("progress", 0) * self.progress
            + weights.get("efficiency", 0) * self.efficiency
            + weights.get("smoothness", 0) * self.smoothness
            + weights.get("prediction_accuracy", 0) * self.prediction_accuracy
        ) / total_weight
        return self.composite

    def to_dict(self) -> dict:
        return {
            "timestamp": self.timestamp,
            "safety": self.safety,
            "progress": self.progress,
            "efficiency": self.efficiency,
            "smoothness": self.smoothness,
            "prediction_accuracy": self.prediction_accuracy,
            "composite": self.composite,
            "notes": self.notes,
        }


@dataclass
class PerformanceCycle:
    """Records one complete sense/think/act cycle with metrics."""
    cycle_number: int = 0
    timestamp: float = 0.0
    sensor_summary: Dict[str, Any] = field(default_factory=dict)
    action_taken: Dict[str, Any] = field(default_factory=dict)
    safety_events: List[str] = field(default_factory=list)
    inference_used: bool = False
    inference_backend: Optional[str] = None
    inference_latency_ms: float = 0.0
    cycle_duration_ms: float = 0.0
    score: Optional[CycleScore] = None


@dataclass
class EvolutionProposal:
    """
    A proposed change generated by the evolution engine.

    Proposals are LOGGED, not auto-applied. Human review is required
    for anything affecting behavior or safety.
    """
    timestamp: float = 0.0
    target: str = ""           # What to change (config key, parameter name)
    current_value: Any = None
    proposed_value: Any = None
    reasoning: str = ""
    expected_improvement: str = ""
    risk_assessment: str = ""
    authorization_required: str = "human"  # "auto" or "human"
    applied: bool = False
    outcome: Optional[str] = None

    def to_dict(self) -> dict:
        return {
            "timestamp": self.timestamp,
            "target": self.target,
            "current_value": self.current_value,
            "proposed_value": self.proposed_value,
            "reasoning": self.reasoning,
            "expected_improvement": self.expected_improvement,
            "risk_assessment": self.risk_assessment,
            "authorization_required": self.authorization_required,
            "applied": self.applied,
            "outcome": self.outcome,
        }


class Evaluator:
    """
    Scores robot performance cycles and tracks trends over time.

    Uses a sliding window of recent scores to detect performance trends.
    When scores trend downward, generates improvement proposals using
    the inference engine.
    """

    def __init__(self, config: dict, logger: Logger) -> None:
        """
        Initialize the evaluator from the 'evolution' section of robot.yaml.

        Args:
            config: The 'evolution' section from robot.yaml
            logger: Logger instance
        """
        self._logger = logger

        # Configuration
        self._window_size = config.get("evaluation_window", 1000)
        self._auto_apply_threshold = config.get("auto_apply_threshold", 0.8)
        self._revert_if_no_improvement = config.get("revert_if_no_improvement", True)
        self._revert_window = config.get("revert_window", 500)

        # Score history (sliding window)
        self._scores: deque = deque(maxlen=self._window_size)
        self._cycle_count = 0

        # Previous action for smoothness calculation
        self._prev_left = 0
        self._prev_right = 0

        # Proposals
        self._proposals: List[EvolutionProposal] = []
        self._pending_proposal: Optional[EvolutionProposal] = None
        self._post_proposal_scores: deque = deque(maxlen=self._revert_window)

        self._logger.log(
            "INFO", "evolution",
            f"Evaluator initialized: window={self._window_size}, "
            f"auto_apply_threshold={self._auto_apply_threshold}",
        )

    def score_cycle(
        self,
        sensor_before: Optional[dict],
        action_taken: dict,
        sensor_after: Optional[dict],
        safety_events: List[str],
    ) -> CycleScore:
        """
        Score a single main-loop cycle on all evaluation dimensions.

        Args:
            sensor_before: Sensor summary dict before the action (simplified).
            action_taken: Dict describing what the robot did.
            sensor_after: Sensor summary dict after the action.
            safety_events: List of safety condition strings from this cycle.

        Returns:
            CycleScore with all dimensions scored.
        """
        self._cycle_count += 1
        score = CycleScore(timestamp=time.time())

        # --- Safety score ---
        if safety_events:
            e_stop_events = [e for e in safety_events if "EMERGENCY" in e or "E_STOP" in e]
            warning_events = [e for e in safety_events if "EMERGENCY" not in e]
            if e_stop_events:
                score.safety = 0.0
                score.notes.append(f"E_STOP triggered: {e_stop_events[0]}")
            elif warning_events:
                score.safety = 0.5
                score.notes.append(f"Safety warning: {warning_events[0]}")
            else:
                score.safety = 0.7
                score.notes.append(f"{len(safety_events)} safety event(s)")
        else:
            score.safety = 1.0

        # --- Progress score ---
        # Simple heuristic: if we are moving and no obstacles, we are making progress
        action_type = action_taken.get("type", "")
        left = action_taken.get("left", 0)
        right = action_taken.get("right", 0)

        if action_type == "set_speed" and (left != 0 or right != 0):
            # Moving — base progress on whether path is clear
            if not safety_events:
                score.progress = 0.8
            else:
                score.progress = 0.3
        elif action_type in ("stop", "e_stop"):
            # Stopped — not making progress but may be correct decision
            if safety_events:
                score.progress = 0.5  # Correct to stop when danger present
            else:
                score.progress = 0.2  # Stopped with no reason
        else:
            score.progress = 0.5  # Neutral

        # --- Efficiency score ---
        # Penalize excessive speed changes and unnecessary actions
        speed_magnitude = abs(left) + abs(right)
        if speed_magnitude == 0 and not safety_events:
            score.efficiency = 0.3  # Idle with no reason is inefficient
            score.notes.append("Idle without safety reason")
        elif speed_magnitude > 0:
            score.efficiency = 0.7  # Moving is generally efficient
        else:
            score.efficiency = 0.5

        # --- Smoothness score ---
        # How much did the motor command change from last cycle?
        delta_left = abs(left - self._prev_left)
        delta_right = abs(right - self._prev_right)
        max_delta = max(delta_left, delta_right)

        if max_delta <= 5:
            score.smoothness = 1.0
        elif max_delta <= 20:
            score.smoothness = 0.8
        elif max_delta <= 50:
            score.smoothness = 0.5
            score.notes.append(f"Large speed change: delta={max_delta}")
        else:
            score.smoothness = 0.2
            score.notes.append(f"Erratic speed change: delta={max_delta}")

        self._prev_left = left
        self._prev_right = right

        # --- Prediction accuracy ---
        # Compare expected sensor change to actual (if both before/after provided)
        if sensor_before is not None and sensor_after is not None:
            score.prediction_accuracy = self._evaluate_prediction(
                sensor_before, sensor_after, action_taken,
            )
        else:
            score.prediction_accuracy = 0.5  # No data, neutral

        # Compute composite
        score.compute_composite()

        # Store in history
        self._scores.append(score)

        # Track post-proposal scores
        if self._pending_proposal is not None:
            self._post_proposal_scores.append(score.composite)

        return score

    def get_session_stats(self) -> dict:
        """
        Aggregate statistics for the current run session.

        Returns:
            Dict with cycle count, averages, trends, and dimension breakdowns.
        """
        if not self._scores:
            return {
                "cycle_count": self._cycle_count,
                "scores_recorded": 0,
                "avg_composite": 0.0,
            }

        composites = [s.composite for s in self._scores]
        safeties = [s.safety for s in self._scores]

        # Trend: compare first half vs second half of window
        n = len(composites)
        if n >= 10:
            first_half = composites[:n // 2]
            second_half = composites[n // 2:]
            trend = sum(second_half) / len(second_half) - sum(first_half) / len(first_half)
        else:
            trend = 0.0

        return {
            "cycle_count": self._cycle_count,
            "scores_recorded": len(self._scores),
            "avg_composite": round(sum(composites) / len(composites), 3),
            "avg_safety": round(sum(safeties) / len(safeties), 3),
            "min_composite": round(min(composites), 3),
            "max_composite": round(max(composites), 3),
            "trend": round(trend, 4),  # Positive = improving, negative = declining
            "proposals_generated": len(self._proposals),
        }

    def propose_improvement(self, session_stats: dict) -> Optional[EvolutionProposal]:
        """
        Analyze accumulated performance and propose a specific improvement.

        This generates a proposal based on score patterns. In a full
        implementation, this would call the inference engine with complexity
        "complex" to get AI-generated proposals. For now, it uses
        rule-based analysis of score dimensions.

        Per Constitution Article 22: Cannot propose weakening safety margins.

        Args:
            session_stats: Output from get_session_stats().

        Returns:
            EvolutionProposal if an improvement is warranted, None otherwise.
        """
        if len(self._scores) < 20:
            return None  # Not enough data

        avg_composite = session_stats.get("avg_composite", 0.5)
        trend = session_stats.get("trend", 0.0)

        # Only propose if performance is declining or consistently poor
        if avg_composite > 0.8 and trend >= 0:
            return None  # Performance is good and stable/improving

        proposal = None

        # Analyze which dimension is weakest
        recent_scores = list(self._scores)[-min(50, len(self._scores)):]

        avg_safety = sum(s.safety for s in recent_scores) / len(recent_scores)
        avg_smoothness = sum(s.smoothness for s in recent_scores) / len(recent_scores)
        avg_efficiency = sum(s.efficiency for s in recent_scores) / len(recent_scores)
        avg_progress = sum(s.progress for s in recent_scores) / len(recent_scores)

        if avg_smoothness < 0.5:
            # Erratic movement — suggest increasing ramp rate limiting
            proposal = EvolutionProposal(
                timestamp=time.time(),
                target="motors.ramp_rate",
                current_value="current",
                proposed_value="reduce by 20%",
                reasoning=(
                    f"Smoothness score averaging {avg_smoothness:.2f} over "
                    f"last {len(recent_scores)} cycles. Motor commands are "
                    f"changing too rapidly between cycles."
                ),
                expected_improvement="smoothness dimension +0.1-0.2",
                risk_assessment="Slower acceleration response. Acceptable trade-off.",
                authorization_required="auto",
            )
        elif avg_efficiency < 0.4:
            # Too much idle time
            proposal = EvolutionProposal(
                timestamp=time.time(),
                target="behavior.idle_threshold",
                current_value="current",
                proposed_value="increase sensitivity to idle detection",
                reasoning=(
                    f"Efficiency score averaging {avg_efficiency:.2f}. "
                    f"Robot spending too many cycles idle without safety reason."
                ),
                expected_improvement="efficiency dimension +0.1-0.2",
                risk_assessment="May increase movement in uncertain situations. Monitor safety.",
                authorization_required="human",
            )
        elif avg_progress < 0.4:
            # Not making progress — possibly stuck or overly cautious
            proposal = EvolutionProposal(
                timestamp=time.time(),
                target="behavior.navigation_strategy",
                current_value="current",
                proposed_value="explore alternative paths when blocked",
                reasoning=(
                    f"Progress score averaging {avg_progress:.2f}. "
                    f"Robot may be stuck in a loop or overly cautious."
                ),
                expected_improvement="progress dimension +0.1-0.3",
                risk_assessment="Alternative paths may have obstacles. Safety monitor will catch.",
                authorization_required="human",
            )
        elif trend < -0.05:
            # General decline
            proposal = EvolutionProposal(
                timestamp=time.time(),
                target="general_performance",
                current_value=f"composite={avg_composite:.2f}",
                proposed_value=f"target composite > {avg_composite + 0.1:.2f}",
                reasoning=(
                    f"Overall performance declining (trend: {trend:+.3f}). "
                    f"Composite score: {avg_composite:.2f}. "
                    f"Recommend detailed analysis with inference engine."
                ),
                expected_improvement="Halt decline, stabilize composite",
                risk_assessment="Requires complex inference call for detailed analysis.",
                authorization_required="human",
            )

        # Constitution Art. 22: NEVER propose reducing safety margins
        if proposal is not None:
            if "safety" in proposal.target.lower() and "reduce" in str(proposal.proposed_value).lower():
                self._logger.log(
                    "WARN", "evolution",
                    "Art. 22 VIOLATION: Rejected proposal to reduce safety margins",
                )
                return None

            self._proposals.append(proposal)
            self._pending_proposal = proposal
            self._post_proposal_scores.clear()

            self._logger.log_evolution(proposal.to_dict())
            self._logger.log(
                "EVOLUTION", "evolution",
                f"Improvement proposed: {proposal.target} — {proposal.reasoning[:100]}",
            )

        return proposal

    def should_propose(self) -> bool:
        """
        Check if enough cycles have elapsed to warrant a new proposal.

        Returns:
            True if evaluation window is complete and proposal is due.
        """
        return (
            self._cycle_count > 0
            and self._cycle_count % self._window_size == 0
        )

    def _evaluate_prediction(
        self,
        before: dict,
        after: dict,
        action: dict,
    ) -> float:
        """
        Compare expected sensor changes to actual changes.

        Simple model: if we moved forward, distances should decrease.
        If we turned, lateral distances should change asymmetrically.

        Returns:
            Score 0.0 to 1.0 for prediction accuracy.
        """
        # Get distances before and after
        us_before = before.get("ultrasonics", {})
        us_after = after.get("ultrasonics", {})

        if not us_before or not us_after:
            return 0.5  # No data to compare

        left_speed = action.get("left", 0)
        right_speed = action.get("right", 0)
        moving_forward = left_speed > 0 and right_speed > 0

        correct_predictions = 0
        total_predictions = 0

        for name in us_before:
            if name in us_after:
                dist_before = us_before.get(name)
                dist_after = us_after.get(name)
                if dist_before is None or dist_after is None:
                    continue

                total_predictions += 1

                # If moving forward, front distances should decrease or stay same
                if moving_forward and "front" in name.lower():
                    if dist_after <= dist_before + 5:  # 5cm tolerance
                        correct_predictions += 1
                else:
                    # For other cases, any stable reading is "correct"
                    if abs(dist_after - dist_before) < 20:
                        correct_predictions += 1

        if total_predictions == 0:
            return 0.5

        return correct_predictions / total_predictions
